name: CI
on:
  push:
    tags: '*'
    branches-ignore:
      - 'autodelivery**'
      - 'bump-**'
      - 'renovate/**'
    paths-ignore:
      - 'CHANGELOG.md'
      - 'LICENSE'
      - 'README.md'
      - 'renovate.json'
  pull_request:
  workflow_dispatch:

jobs:
  Build:
    if: contains(github.repository, 'sample-gradle-project') && !github.event.repository.fork
    strategy:
      matrix:
        os: [windows, macos, ubuntu]
        jvm_version: [11, 16, 17, 18]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout
        uses: DanySK/action-checkout@0.2.3
      - uses: DanySK/build-check-deploy-gradle-action@2.1.14
        with:
          custom-secret-0: ${{ secrets.OMDB_API_KEY }}
          java-version: ${{ matrix.jvm_version }}
          check-command: true
          deploy-command: |
            export OMDB_API_KEY="$CUSTOM_SECRET_0"
            ./gradlew check
          should-run-codecov: false
          should-deploy: true
          should-validate-wrapper: ${{ matrix.os == 'ubuntu' && matrix.jvm_version == '17' }}
